version: '3.8'

name: kafka-kraft-cluster
services:
  kafka-node-1:
    image: bitnami/kafka:latest
    container_name: kafka-node-1
    environment:
      KAFKA_CFG_KRAFT_MODE: "true"
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka-node-1:9093,2@kafka-node-2:9093
      KAFKA_CFG_LISTENERS: CONTROLLER://kafka-node-1:9093,DOCKER://kafka-node-1:9094,HOST://0.0.0.0:9192
      KAFKA_CFG_ADVERTISED_LISTENERS: DOCKER://kafka-node-1:9094,HOST://localhost:9192
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,HOST:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CLUSTER_ID: 5f0330bf-9411-4438-a0fa-b4fd5baf7d28
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9192:9192"
    volumes:
      - kafka-node-1-data:/bitnami/kafka
    networks:
      - my-network

  kafka-node-2:
    image: bitnami/kafka:latest
    container_name: kafka-node-2
    environment:
      KAFKA_CFG_KRAFT_MODE: "true"
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_NODE_ID: 2
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka-node-1:9093,2@kafka-node-2:9093
      KAFKA_CFG_LISTENERS: CONTROLLER://kafka-node-2:9093,DOCKER://kafka-node-2:9094,HOST://0.0.0.0:9193
      KAFKA_CFG_ADVERTISED_LISTENERS: DOCKER://kafka-node-2:9094,HOST://localhost:9193
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,HOST:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CLUSTER_ID: 5f0330bf-9411-4438-a0fa-b4fd5baf7d28
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9193:9193"
    volumes:
      - kafka-node-2-data:/bitnami/kafka
    networks:
      - my-network

volumes:
  kafka-node-1-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: E:\kafka-data\node-1
  kafka-node-2-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: E:\kafka-data\node-2

networks:
  my-network:
    external: true